### ISSUE TITLE
Next Shared Project?

### ISSUE THREAD

**Issue by jspeed-meyers** [Open-Source-Software-Neighborhood-Watch/town-square#7]
For this Wednesday's meeting, I propose discussing what our next shared project ought to be. I was thinking it would be fun to write a "Does the Military Need an Open Source Program Office?" essay. It would describe what a military OSPO would look like and discuss the pros and cons.

@jackiekazil, @tpike3

wdyt?

Also, I cleaned up the repos over the past couple weeks, archiving a couple and adding CODEOWNERS files. Additionally, I added a csv file that describes the status of each project.

**Comment by jspeed-meyers** [comment]
Add @gps-iqt-labs too!

**Comment by jspeed-meyers** [comment]
Thought I would drop @tpike3's related comment here for ease of tracking discussion:

> For next steps... in my mind I am thinking lit review what are all the efforts out there both corporate and not corporate, efforts for recognition and compensation etc.

I agree! That would be a helpful step.

**Comment by gps-iqt-labs** [comment]
ICYMI, one of the talks at GitHub Universe 2021 gave a great OSPO overview:
- summary: [https://githubuniverse.com/content-library/live-qa-building-an-ospo/](https://githubuniverse.com/content-library/live-qa-building-an-ospo/)
- accompanying background: [https://thenewstack.io/more-organizations-report-benefits-of-open-source-programs](https://thenewstack.io/more-organizations-report-benefits-of-open-source-programs)
- Q&A with TODO Group and RedMonk [https://youtu.be/csBlQrGXH1o](https://youtu.be/csBlQrGXH1o)

**Comment by gps-iqt-labs** [comment]
Two more references that seem relevant:

- [OSPOlogy: How to start an OSPO Program](https://www.youtube.com/watch?v=SVvIUdAvBw0)
- [Leveraging the Open Source Program Office: New Research Unpacks the Evolution of the OSPO (and a Whole Lot More)](https://www.linuxfoundation.org/blog/leveraging-the-open-source-program-office-new-research-unpacks-the-evolution-of-the-ospo-and-a-whole-lot-more/)

**Comment by jspeed-meyers** [comment]
Since we have decided on some initial pieces of writing and some initial metrics/OKRs for April 2022 - September 2022, I am closing this issue. Anyone should feel free to reopen this, especially if we pursue the OSPO idea.
